name: CI/CD for Apache Beam Project

on:
  pull_request:
    branches:
      - main

  workflow_run:
    workflows:
      - CI/CD for Apache Beam Project
    types:
      - completed

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Run tests
        run: |
          pytest tests/

  manual-approval:
    name: Manual Approval
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Await manual approval
        run: echo "Awaiting approval for production deployment."
        if: success()

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: manual-approval

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/
